- name: create helloword
  hosts: all
  vars: 
    file_path: /etc/hellowordawxxx
    
  tasks:
    - name: create file
      ansible.builtin.file:
        path: '{{ file_path }}'
        state: touch
